### ISSUE TITLE
list not updating when new link is entered

### ISSUE THREAD

**Issue by j2l** [brentvatne/hackernews-react-native-apollo#4]
I successfully changed the graphcool uri to mine (and rebuilt all fields) so I can start with a brand new  list. It's working fine.
But now since list is not crowded I notice that update is not automatic when a new link ins entered.
I need to pull down to refresh the list and get the last item.

**Comment by brentvatne** [comment]
this happens because we can't guess where in the list of top links a new one should go, this is determined by the [votes webtask](https://github.com/brentvatne/hackernews-react-native-apollo/tree/master/webtasks/votes) asynchronously. so instead i made it so that when you submit a link it jumps to the new links screen, and puts your new link at the top
